name: ethiopia
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^8.5.0
  google_fonts: ^2.1.0
  path_provider: ^2.0.2
  readmore: ^2.1.0
  platform_maps_flutter: ^1.0.1
  google_maps: ^5.1.0
  introduction_screen: ^2.1.0
  flutter_icons: ^1.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/abay/abay_1.jpg
    - assets/images/afar/afar_1.png
    - assets/images/afar/afar_2.jpg
    - assets/images/afar/afar_3.jpg
    - assets/images/axum/axum_1.jpg
    - assets/images/axum/axum_2.jpg
    - assets/images/axum/axum_1.jpg
    - assets/images/ethiopia/ethiopia_1.jpg
    - assets/images/ethiopia/ethiopia_2.png
    - assets/images/ethiopia/ethiopia_3.jpg
    - assets/images/ethiopia/ethiopia_4.jpg
    - assets/images/ethiopia/ethiopia_5.jpg
    - assets/images/fasiledes/fasil_1.jpg
    - assets/images/gonder/gonder_1.jpg
    - assets/images/gonder/gonder_2.jpg
    - assets/images/gonder/gonder_3.jpg
    - assets/images/harar/harar_1.jpg
    - assets/images/harar/harar_2.jpg
    - assets/images/harar/harar_3.jpg
    - assets/images/harar/harar_4.jpg
    - assets/images/harar/harar_5.jpg
    - assets/images/harar/harar_6.jpg
    - assets/images/lalibela/lalibela_1.jpg
    - assets/images/lalibela/lalibela_2.jpg
    - assets/images/lalibela/lalibela_3.jpg
    - assets/images/mesekel/mesekel_1.png
    - assets/images/mesekel/mesekel_2.png
    - assets/images/mesekel/mesekel_3.jpg
    - assets/images/mesekel/mesekel_4.jpg
    - assets/images/mesekel/mesekel_5.png
    - assets/images/mesekel/mesekel_6.jpg
    - assets/images/new year/new_year_1.jpg
    - assets/images/new year/new_year_2.jpg
    - assets/images/other/other_1.jpg
    - assets/images/other/other_2.jpg
    - assets/images/other/other_3.jpg
    - assets/images/people/AD_1.jpg
    - assets/images/people/AD_2.jpg
    - assets/images/people/HD_1.jpg
    - assets/images/people/meles_1.jpg
    - assets/images/people/meles_2.jpg
    - assets/images/people/meles_3.jpg
    - assets/images/timket/timket_1.jpg
    - assets/images/timket/timket_2.jpg
    - assets/images/timket/timket_3.jpg
    - assets/images/timket/timket_4.jpg
    - assets/images/timket/timket_5.jpg
    - assets/images/timket/timket_6.jpg
    - assets/images/timket/timket_7.jpg
    - assets/images/timket/timket_8.png
    - assets/images/timket/timket_9.jpg
    - assets/images/ethiopia/ethiopia_2.png
    - assets/images/tewodros/Tewodros_1.jpg
    - assets/images/menilik/menilik_1.jpg
    - assets/images/hileSelase/haileSelase_1.jpg
    - assets/images/mengestuHileMariyam/mengestuHileMariam_1.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
